# Generated by Django 5.0.6 on 2024-05-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
