# Generated by Django 5.0.6 on 2024-05-31 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_location_journey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_journeys', to=settings.AUTH_USER_MODEL),
        ),
    ]
