# Generated by Django 5.0.6 on 2024-06-01 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_journey_end_date_alter_journey_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
